// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chiren-c/chili/bff/ioc"
	"github.com/chiren-c/chili/bff/web/jwt"
	"github.com/chiren-c/chili/bff/web/user"
	"github.com/chiren-c/chili/pkg/bootstrap"
	"github.com/chiren-c/chili/user/repository"
	"github.com/chiren-c/chili/user/repository/dao"
	"github.com/chiren-c/chili/user/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *bootstrap.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	userDAO := dao.NewGORMUserDAO(db)
	userRepository := repository.NewCacheUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := user.NewUserHandler(logger, userService, handler)
	server := ioc.InitGinServer(userHandler, handler, logger, cmdable)
	app := &bootstrap.App{
		WebServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitRedis)
