// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	repository3 "github.com/chiren-c/chili/article/repository"
	cache2 "github.com/chiren-c/chili/article/repository/cache"
	dao2 "github.com/chiren-c/chili/article/repository/dao"
	service3 "github.com/chiren-c/chili/article/service"
	"github.com/chiren-c/chili/bff/ioc"
	"github.com/chiren-c/chili/bff/web/article"
	"github.com/chiren-c/chili/bff/web/jwt"
	"github.com/chiren-c/chili/bff/web/user"
	repository2 "github.com/chiren-c/chili/code/repository"
	"github.com/chiren-c/chili/code/repository/cache"
	service2 "github.com/chiren-c/chili/code/service"
	"github.com/chiren-c/chili/pkg/bootstrap"
	"github.com/chiren-c/chili/user/repository"
	"github.com/chiren-c/chili/user/repository/dao"
	"github.com/chiren-c/chili/user/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *bootstrap.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	userDAO := dao.NewGORMUserDAO(db)
	userRepository := repository.NewCacheUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	serviceService := ioc.InitSmsTencentService()
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository2.NewCachedCodeRepository(codeCache)
	codeService := service2.NewSMSCodeService(serviceService, codeRepository)
	userHandler := user.NewUserHandler(logger, userService, handler, codeService)
	articleAuthorDAO := dao2.NewGORMArticleAuthorDAO(db)
	articleAuthorCache := cache2.NewRedisArticleAuthor(cmdable)
	articleAuthorRepository := repository3.NewArticleAuthorRepository(logger, articleAuthorDAO, articleAuthorCache)
	articleService := service3.NewArticleService(logger, articleAuthorRepository)
	articleHandler := article.NewArticleHandler(logger, articleService)
	server := ioc.InitGinServer(userHandler, articleHandler, handler, logger, cmdable)
	app := &bootstrap.App{
		WebServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitRedis)
